In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from tqdm import tqdm
import numpy as np
from LoRR_MAPF.envs import FollowerLoRR

# Define a temporary map for testing
test_domain_path = "../../../example_problems/empty.domain"
test_map_name = "empty_8_8.map"
num_agents = 3
agents_pos = np.array([[0, 0], [1, 2], [0, 2]])
agents_dir = np.array([2, 1, 0])
tasks_pos = np.array([[[7, 0], [7, 1], [7, 2]], [[0, 0], [0, 1], [0, 2]]])

# Create test domain and map files
# Instantiate and test the environment
env = FollowerLoRR(
    domain_path=test_domain_path,
    num_agents=num_agents,
    map_name=test_map_name,
    render_mode="human",
    block_all_actions=False,
    agents_pos=agents_pos,
    agents_dir=agents_dir,
    tasks_pos=tasks_pos,
    stray_penalty=0,
)
# env = LoRR(domain_path=test_domain_path, num_agents=500, map_name=test_map_name, render_mode="human")

obs, info = env.reset()  # Reset the environment
print(f"Initial observation: {obs}")

# for _ in tqdm(range(5000)):  # Run a few steps
#     action = env.action_space.sample()  # Sample a random action
#     env.step(action)
#     # env.render()


/Users/alejandroaristizabal/Documents/LORR24_aristizabal95/python/env/LoRR_MAPF/utils/planner_utils.py:384: NumbaTypeSafetyWarning: unsafe cast from Tuple(UniTuple(int64 x 2), int64) to Tuple(UniTuple(int32 x 2), int32). Precision may be lost.
  curr = parent[curr]
/Users/alejandroaristizabal/Documents/LORR24_aristizabal95/python/env/LoRR_MAPF/utils/planner_utils.py:384: NumbaTypeSafetyWarning: unsafe cast from Tuple(UniTuple(int64 x 2), int64) to Tuple(UniTuple(int32 x 2), int32). Precision may be lost.
  curr = parent[curr]
/Users/alejandroaristizabal/Documents/LORR24_aristizabal95/python/env/LoRR_MAPF/utils/planner_utils.py:384: NumbaTypeSafetyWarning: unsafe cast from Tuple(UniTuple(int64 x 2), int64) to Tuple(UniTuple(int32 x 2), int32). Precision may be lost.
  curr = parent[curr]


Initial observation: [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  ...

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
  

In [4]:
obs[0][3]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [5]:
next_obs, reward, terminated, truncated, info = env.step(np.array([3, 3, 1]))

In [6]:
next_obs[0][3]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [8]:
reward[0]

np.float64(-1.0)

In [7]:
env.render()

In [17]:
env.reset()

(array([[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 1., 0.],
          [0.

In [9]:
env.close()